#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Jan 04, 2023 09:15:59 AM EST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path
import config

_script = sys.argv[0]
_location = os.path.dirname(_script)

import WR9RrigAuto_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        # top.geometry("500x280+30+700")
        # top.minsize(120, 1)
        # top.maxsize(5764, 1070)
        # top.resizable(1,  1)
        # top.title("WR9R_Automation_V1")
        # top.configure(background="#a4a4a4")
        # top.configure(highlightbackground="#d9d9d9")
        # top.configure(highlightcolor="black")
   
        top.geometry("499x267+13+724")
        top.minsize(120, 1)
        top.maxsize(5764, 1070)
        top.resizable(1,  1)
        top.title("WR9R_Automation_V1")
        top.configure(background="#4a4a4a")
        top.configure(highlightbackground="#4e4e4e")
        top.configure(highlightcolor="black")

        self.top = top
        self.FullAuto = tk.IntVar()
        self.KATButton = tk.IntVar()
        self.selectedButton = tk.IntVar()

        self.Message1 = tk.Message(self.top)
        self.Message1.place(relx=0.441, rely=0.112, relheight=0.109
                , relwidth=0.166)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(padx="1")
        self.Message1.configure(pady="1")
        self.Message1.configure(text=''' ''')
        self.Message1.configure(width=100)

        self.Message2 = tk.Message(self.top)
        self.Message2.place(relx=0.401, rely=0.262, relheight=0.109
                , relwidth=0.24)
        self.Message2.configure(background="#d9d9d9")
        self.Message2.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(padx="1")
        self.Message2.configure(pady="1")
        self.Message2.configure(text=''' ''')
        self.Message2.configure(width=100)

        self.Checkbutton1 = tk.Checkbutton(self.top)
        self.Checkbutton1.place(relx=0.421, rely=0.412, relheight=0.09
                , relwidth=0.212)
        self.Checkbutton1.configure(activebackground="beige")
        self.Checkbutton1.configure(activeforeground="black")
        self.Checkbutton1.configure(anchor='w')
        self.Checkbutton1.configure(background="#d9d9d9")
        self.Checkbutton1.configure(command=WR9RrigAuto_support.AutoStatus)
        self.Checkbutton1.configure(compound='left')
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(selectcolor="#d9d9d9")
        self.Checkbutton1.configure(text='''Full Auto''')
        self.Checkbutton1.configure(variable=self.FullAuto)

        self.Frame2 = tk.Frame(self.top)
        self.Frame2.place(relx=0.08, rely=0.06, relheight=0.331, relwidth=0.251)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")
        self.Radiobutton1 = tk.Radiobutton(self.Frame2)
        self.Radiobutton1.place(relx=0.08, rely=0.091, relheight=0.236
                , relwidth=0.464)
        self.Radiobutton1.configure(activebackground="beige")
        self.Radiobutton1.configure(activeforeground="black")
        self.Radiobutton1.configure(anchor='w')
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(command=WR9RrigAuto_support.KAT500_Select)
        self.Radiobutton1.configure(compound='left')
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(selectcolor="#d9d9d9")
        self.Radiobutton1.configure(text='''ANT-1''')
        self.Radiobutton1.configure(value='1')
        self.Radiobutton1.configure(variable=self.KATButton)
        self.Radiobutton2 = tk.Radiobutton(self.Frame2)
        self.Radiobutton2.place(relx=0.08, rely=0.364, relheight=0.245
                , relwidth=0.464)
        self.Radiobutton2.configure(activebackground="beige")
        self.Radiobutton2.configure(activeforeground="black")
        self.Radiobutton2.configure(anchor='w')
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(command=WR9RrigAuto_support.KAT500_Select)
        self.Radiobutton2.configure(compound='left')
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(selectcolor="#d9d9d9")
        self.Radiobutton2.configure(text='''ANT-2''')
        self.Radiobutton2.configure(value='2')
        self.Radiobutton2.configure(variable=self.KATButton)
        self.Radiobutton3 = tk.Radiobutton(self.Frame2)
        self.Radiobutton3.place(relx=0.08, rely=0.636, relheight=0.245
                , relwidth=0.464)
        self.Radiobutton3.configure(activebackground="beige")
        self.Radiobutton3.configure(activeforeground="black")
        self.Radiobutton3.configure(anchor='w')
        self.Radiobutton3.configure(background="#d9d9d9")
        self.Radiobutton3.configure(command=WR9RrigAuto_support.KAT500_Select)
        self.Radiobutton3.configure(compound='left')
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(foreground="#000000")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="black")
        self.Radiobutton3.configure(justify='left')
        self.Radiobutton3.configure(selectcolor="#d9d9d9")
        self.Radiobutton3.configure(text='''ANT-3''')
        self.Radiobutton3.configure(value='3')
        self.Radiobutton3.configure(variable=self.KATButton)
        self.Frame3 = tk.Frame(self.top)
        self.Frame3.place(relx=0.08, rely=0.401, relheight=0.578, relwidth=0.251)

        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#d9d9d9")
        self.Frame3.configure(highlightbackground="#d9d9d9")
        self.Frame3.configure(highlightcolor="black")
        self.Radiobutton4 = tk.Radiobutton(self.Frame3)
        self.Radiobutton4.place(relx=0.08, rely=0.052, relheight=0.151
                , relwidth=0.784)
        self.Radiobutton4.configure(activebackground="beige")
        self.Radiobutton4.configure(activeforeground="black")
        self.Radiobutton4.configure(anchor='w')
        self.Radiobutton4.configure(background="#d9d9d9")
        self.Radiobutton4.configure(command=WR9RrigAuto_support.WR9R_Select)
        self.Radiobutton4.configure(compound='left')
        self.Radiobutton4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton4.configure(foreground="#000000")
        self.Radiobutton4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton4.configure(highlightcolor="black")
        self.Radiobutton4.configure(justify='left')
        self.Radiobutton4.configure(selectcolor="#d9d9d9")
        self.Radiobutton4.configure(text='''WR9R-1''')
        self.Radiobutton4.configure(value='1')
        self.Radiobutton4.configure(variable=self.selectedButton)
        self.Radiobutton5 = tk.Radiobutton(self.Frame3)
        self.Radiobutton5.place(relx=0.08, rely=0.219, relheight=0.156
                , relwidth=0.864)
        self.Radiobutton5.configure(activebackground="beige")
        self.Radiobutton5.configure(activeforeground="black")
        self.Radiobutton5.configure(anchor='w')
        self.Radiobutton5.configure(background="#d9d9d9")
        self.Radiobutton5.configure(command=WR9RrigAuto_support.WR9R_Select)
        self.Radiobutton5.configure(compound='left')
        self.Radiobutton5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton5.configure(foreground="#000000")
        self.Radiobutton5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton5.configure(highlightcolor="black")
        self.Radiobutton5.configure(justify='left')
        self.Radiobutton5.configure(selectcolor="#d9d9d9")
        self.Radiobutton5.configure(text='''WR9R-2''')
        self.Radiobutton5.configure(value='2')
        self.Radiobutton5.configure(variable=self.selectedButton)
        self.Radiobutton6 = tk.Radiobutton(self.Frame3)
        self.Radiobutton6.place(relx=0.08, rely=0.385, relheight=0.151
                , relwidth=0.784)
        self.Radiobutton6.configure(activebackground="beige")
        self.Radiobutton6.configure(activeforeground="black")
        self.Radiobutton6.configure(anchor='w')
        self.Radiobutton6.configure(background="#d9d9d9")
        self.Radiobutton6.configure(command=WR9RrigAuto_support.WR9R_Select)
        self.Radiobutton6.configure(compound='left')
        self.Radiobutton6.configure(disabledforeground="#a3a3a3")
        self.Radiobutton6.configure(foreground="#000000")
        self.Radiobutton6.configure(highlightbackground="#d9d9d9")
        self.Radiobutton6.configure(highlightcolor="black")
        self.Radiobutton6.configure(justify='left')
        self.Radiobutton6.configure(selectcolor="#d9d9d9")
        self.Radiobutton6.configure(text='''WR9R-3''')
        self.Radiobutton6.configure(value='3')
        self.Radiobutton6.configure(variable=self.selectedButton)
        self.Radiobutton7 = tk.Radiobutton(self.Frame3)
        self.Radiobutton7.place(relx=0.08, rely=0.547, relheight=0.156
                , relwidth=0.864)
        self.Radiobutton7.configure(activebackground="beige")
        self.Radiobutton7.configure(activeforeground="black")
        self.Radiobutton7.configure(anchor='w')
        self.Radiobutton7.configure(background="#d9d9d9")
        self.Radiobutton7.configure(command=WR9RrigAuto_support.WR9R_Select)
        self.Radiobutton7.configure(compound='left')
        self.Radiobutton7.configure(disabledforeground="#a3a3a3")
        self.Radiobutton7.configure(foreground="#000000")
        self.Radiobutton7.configure(highlightbackground="#d9d9d9")
        self.Radiobutton7.configure(highlightcolor="black")
        self.Radiobutton7.configure(justify='left')
        self.Radiobutton7.configure(selectcolor="#d9d9d9")
        self.Radiobutton7.configure(text='''WR9R-4''')
        self.Radiobutton7.configure(value='4')
        self.Radiobutton7.configure(variable=self.selectedButton)
        self.Radiobutton8 = tk.Radiobutton(self.Frame3)
        self.Radiobutton8.place(relx=0.08, rely=0.714, relheight=0.156
                , relwidth=0.864)
        self.Radiobutton8.configure(activebackground="beige")
        self.Radiobutton8.configure(activeforeground="black")
        self.Radiobutton8.configure(anchor='w')
        self.Radiobutton8.configure(background="#d9d9d9")
        self.Radiobutton8.configure(command=WR9RrigAuto_support.WR9R_Select)
        self.Radiobutton8.configure(compound='left')
        self.Radiobutton8.configure(disabledforeground="#a3a3a3")
        self.Radiobutton8.configure(foreground="#000000")
        self.Radiobutton8.configure(highlightbackground="#d9d9d9")
        self.Radiobutton8.configure(highlightcolor="black")
        self.Radiobutton8.configure(justify='left')
        self.Radiobutton8.configure(selectcolor="#d9d9d9")
        self.Radiobutton8.configure(text='''WR9R-5''')
        self.Radiobutton8.configure(value='5')
        self.Radiobutton8.configure(variable=self.selectedButton)
        # self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        # top.configure(menu = self.menubar)

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.701, rely=0.151, height=54, width=107)
        self.Button1.configure(activebackground="beige")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=WR9RrigAuto_support.TunerUP)
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Tune!''')

        self.Button3 = tk.Button(self.top)
        self.Button3.place(relx=0.701, rely=0.633, height=54, width=107)
        self.Button3.configure(activebackground="beige")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(command=WR9RrigAuto_support.JustLeave)
        self.Button3.configure(compound='left')
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Exit''')

def start_up():
    WR9RrigAuto_support.main()

if __name__ == '__main__':
    WR9RrigAuto_support.main()




